query getUsers {
  users {
    id
    name
    email
    role
    avatar
    creationAt
  }
}

query getUser($id: ID!) {
  user(id: $id) {
    id
    name
    email
    role
    avatar
  }
}

mutation signUp($password: String!, $email: String!, $name: String!) {
  addUser(
    data: {
      name: $name
      email: $email
      password: $password
      avatar: "https://png.pngtree.com/png-vector/20191101/ourmid/pngtree-cartoon-color-simple-male-avatar-png-image_1934459.jpg"
      role: admin
    }
  ) {
    id
    name
    email
    avatar
  }
}

mutation login($password: String!, $email: String!) {
  login(email: $email, password: $password) {
    access_token
    refresh_token
  }
}
